### ISSUE TITLE
[FEATURE] Red and green areas should not overlap

### ISSUE THREAD

**Issue by jschirrmacher** [jschirrmacher/timer#5]
Currently, the red and the green areas overlap, leaving a rather brownish look for the remaining time period. It would be nice, if the green area and the red area would adjoin each other.

**Comment by Chrigerigk** [comment]
additionally: it would be great if the green area would vanish after the time box reached its end.

**Comment by jschirrmacher** [comment]
Vanishing of the areas after time is up should be solved in the most current version

**Comment by jschirrmacher** [comment]
Solved by #11
